name: release to NuGet

on:
  push:

jobs:

  deploy:
    runs-on: windows-latest
    continue-on-error: false

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Download artifacts"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/NREL/OpenStudio/actions/artifacts/761132260/zip
          
          ls -r
          
