name: release to NuGet

on:
  push:

jobs:

  deploy:
    runs-on: windows-latest
    continue-on-error: false

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Download artifacts"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh run download 5120080246 -n CSharp_Windows_x64x86 --dir . --repo NREL/OpenStudio
          ls
      
      - name: "Update package"
        run: |
          dotnet run --project OpenStudio.NuGet.Publisher\OpenStudio.NuGet.Publisher.csproj "NREL.OpenStudio.win" "3.6.1" "2023"
          ls -r

      - name: "Publish"
        run: |
          dotnet nuget push NREL.OpenStudio.win.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
          
