env:
  RUN_ID: 9189117111
  VERSION: "3.8.0"

name: release to NuGet
on:
  push:

jobs:

  deploy:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        include:
        - os: windows-latest
          NuGetID: "NREL.OpenStudio.win"
          ArtifactName: "CSharp_Windows_x64x86"
        - os: macos-11
          NuGetID: "NREL.OpenStudio.macOS-x64"
          ArtifactName: "CSharp_macOS"
        - os: ubuntu-latest
          NuGetID: "NREL.OpenStudio.linux-x64"
          ArtifactName: "CSharp_Ubuntu"
        - os: macos-14
          NuGetID: "NREL.OpenStudio.macOS-arm64"
          ArtifactName: "CSharp_macOS_arm64"


    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Download artifacts"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh run download ${{ env.RUN_ID }} -n ${{matrix.ArtifactName}} --dir . --repo NREL/OpenStudio
          ls
      
      - name: "Unzip artifact"
        if: runner.os != 'Windows'
        run: |
          7z e ${{matrix.ArtifactName}}.zip -o.
          ls -r
      
      - name: "Update package"
        run: |
          dotnet run --project OpenStudio.NuGet.Publisher/OpenStudio.NuGet.Publisher.csproj ${{ matrix.NuGetID }} ${{ env.VERSION }}
          ls -r

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.NuGetID }}
          path: ${{ matrix.NuGetID }}.*.nupkg

      - name: "Publish"
        run: |
          dotnet nuget push ${{ matrix.NuGetID }}.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
          
